### ISSUE TITLE
Variable fonts

### ISSUE THREAD

**Issue by brycewray** [supernotes/sn-pro#1]
As @tobeagram [suggested on Hacker News](https://news.ycombinator.com/item?id=39467099), I am filing an issue regarding the release of variable versions (both regular and italicized) of the SN Pro typeface. Having variable fonts obviously will be far preferable, especially regarding performance, to forcing numerous **non**-variable downloads on visitors to sites which use a wider variety of font weights.

Very nice work so far!

**Comment by tobeagram** [comment]
Thanks for opening the first issue @brycewray 🥳

In a future update we will add WIP variable fonts for everyone to test. Once we're happy with them we will include them in the .zip for everyone.

**Comment by tobeagram** [comment]
I've just pushed WIP variable fonts as [.woff](https://github.com/supernotes/sn-pro/blob/next/exports/SNPro/SNPro-Variable.woff) and [.woff2](https://github.com/supernotes/sn-pro/blob/next/exports/SNPro/SNPro-Variable.woff2) on the new [`next`](https://github.com/supernotes/sn-pro/tree/next) branch. Please trial them out and let me know if you have any feedback! 🙌

If you'd like to include them in css please follow the following guidelines. This allows support for all weights and italics in almost all major browsers:

```css
@font-face {
  font-family: 'SN Pro';
  src: url(SNProVF_LINK) format('woff2-variations');
  font-weight: 200 900;
  font-style: oblique 0deg 14deg;
}
```
